//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CG_2nd.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CG_2ndTYPE                  130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_TRAN                 310
#define IDD_DIALOG_SCALE                311
#define IDD_DIALOG_PIVOT                312
#define IDD_DIALOG_AXIS                 313
#define IDD_DIALOG_RANDOM               314
#define IDR_HTML_SCALING                315
#define IDD_DIALOG_ORTHO                316
#define IDD_DIALOG_FRUSTUM              318
#define IDD_DIALOG_PERSPECTIVE          319
#define IDD_DIALOG_Camera_POSITION      320
#define IDD_DIALOG_Camera_POS           320
#define IDD_DIALOG_CAMERA               320
#define IDD_DIALOG_LIGHT_POS            321
#define IDD_DIALOG_LIGHT_COLOR          322
#define IDC_EDIT_X                      1000
#define IDC_EDIT_Y                      1001
#define IDC_EDIT_Z                      1002
#define IDC_BUTTON_OK                   1003
#define IDC_BUTTON_CANCEL               1004
#define IDC_STATIC_X                    1005
#define IDC_STATIC_Y                    1006
#define IDC_STATIC_Z                    1007
#define IDC_EDIT_PIVOT_X                1008
#define IDC_STATIC_X5                   1008
#define IDC_STATIC_Z4                   1008
#define IDC_EDIT_PIVOT_Y                1009
#define IDC_EDIT_FOC_X                  1009
#define IDC_STATIC_D_G                  1009
#define IDC_EDIT_P                      1009
#define IDC_EDIT_PIVOT_Z                1010
#define IDC_STATIC_Y3                   1010
#define IDC_STATIC_D_B                  1010
#define IDC_EDIT_X1                     1011
#define IDC_EDIT_FOC_Y                  1011
#define IDC_STATIC_S_R                  1011
#define IDC_EDIT_ANGLE                  1012
#define IDC_STATIC_Z3                   1012
#define IDC_STATIC_S_G                  1012
#define IDC_EDIT_Y1                     1013
#define IDC_EDIT_FOC_Z                  1013
#define IDC_STATIC_S_B                  1013
#define IDC_STATIC_X2                   1014
#define IDC_EDIT_Z1                     1014
#define IDC_EDIT_LEFT                   1015
#define IDC_EDIT_UP_X                   1015
#define IDC_STATIC_Y2                   1016
#define IDC_EDIT_RIGHT                  1017
#define IDC_EDIT_UP_Y                   1017
#define IDC_STATIC_Z2                   1018
#define IDC_EDIT_BOTTOM                 1019
#define IDC_EDIT_UP_Z                   1019
#define IDC_EDIT_TOP                    1020
#define IDC_STATIC_A_A                  1020
#define IDC_EDIT_NEAR                   1021
#define IDC_STATIC_D_A                  1021
#define IDC_EDIT_FAR                    1022
#define IDC_STATIC_S_A                  1022
#define IDC_EDIT_ASPECT                 1023
#define IDC_EDIT_FOV                    1024
#define IDC_EDIT_POS_X                  1025
#define IDC_EDIT_POS_Y                  1026
#define IDC_EDIT_POS_Z                  1027
#define IDC_STATIC_X3                   1028
#define IDC_EDIT_AMBIENT_A              1028
#define IDC_EDIT_X2                     1029
#define IDC_EDIT_DIFFUSE_R              1029
#define IDC_EDIT_DIFFUSE_G              1030
#define IDC_EDIT_Y2                     1031
#define IDC_EDIT_DIFFUSE_B              1031
#define IDC_EDIT_DIFFUSE_A              1032
#define IDC_EDIT_Z2                     1033
#define IDC_EDIT_SPECULAR_R             1033
#define IDC_STATIC_X4                   1034
#define IDC_EDIT_SPECULAR_G             1034
#define IDC_EDIT_SPECULAR_B             1035
#define IDC_EDIT_SPECULAR_A             1036
#define IDC_STATIC_A_R                  1037
#define IDC_STATIC_A_G                  1038
#define IDC_STATIC_A_B                  1039
#define IDC_STATIC_D_R                  1040
#define IDC_EDIT_AMBIENT_R              1041
#define IDC_EDIT_AMBIENT_G              1042
#define IDC_EDIT_AMBIENT_B              1043
#define ID_MESHLOADER_DRAWFACENORMALVECTORS 32771
#define ID_MESHLOADER_FACENORMALVECTORS 32772
#define ID_LOAD_QUAD                    32773
#define ID_LOAD_VECTOR                  32774
#define ID_LOAD_WIRE                    32775
#define ID_EDIT_POINTS                  32776
#define ID_LOAD_POINTS                  32777
#define ID_LOAD_POINT                   32778
#define ID_3DVIEWING_ORTHOGRAPHIC       32779
#define ID_3DVIEWING_PERSPECTIVE        32780
#define ID_3DVIEWING_FRUSTUM            32781
#define ID_TRANSFORMATION_TRANSLATION   32782
#define ID_TRANSFORMATION_SCALING       32783
#define ID_TRANSFORMATION_PIVOT         32784
#define ID_TRANSFORMATION_X             32785
#define ID_TRANSFORMATION_ARBITRARYAXISROTATION 32786
#define ID_TRANSFORM_TRANS              32787
#define ID_TRANSFORM_SCALING            32788
#define ID_TRANSFORM_SCALE              32789
#define ID_TRANSFORM_PIVOT              32790
#define ID_TRANSFORM_Axis               32791
#define ID_TRANSFORM_RANDOM             32792
#define ID_FILE_OPEN32793               32793
#define ID_FILE_EXIT                    32794
#define ID_FILE_OPEN_1                  32795
#define ID_FILE_OPEN_3                  32796
#define ID_CAMERA_POSITION              32797
#define ID_TEXTURE_OPEN                 32798
#define ID_TEXTURE_ENABLE               32799
#define ID_SHADING_FLAT                 32800
#define ID_SHADING_GOURAUD              32801
#define ID_SHADING_GOURAUD32802         32802
#define ID_LIGHT_POSITION               32803
#define ID_LIGHT_COLOR                  32804
#define ID_MULTIVIEW_ENABLE             32805
#define ID_CAMERA_ROTATION              32806
#define ID_SHADING_NONE                 32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           316
#endif
#endif
